import type { Plant } from '../types';

export const poisonousPlants: Plant[] = [
    {
        id: 1,
        name: "Arum",
        commonNames: ["Adam-and-Eve", "Lord-and-Ladies", "Wake Robin", "Starch Root", "Bobbins", "Cuckoo Plant"],
        scientificName: "Arum maculatum",
        family: "Araceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/adam-and-eve"
    },
    {
        id: 2,
        name: "African Wonder Tree",
        commonNames: [],
        scientificName: "Ricinus communis",
        family: "Euphorbiaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/african-wonder-tree"
    },
    {
        id: 3,
        name: "Alocasia",
        commonNames: ["Elephant's Ear"],
        scientificName: "Alocasia spp.",
        family: "Araceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/alocasia"
    },
    {
        id: 4,
        name: "Aloe",
        commonNames: ["Aloe Vera"],
        scientificName: "Aloe vera",
        family: "Liliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/aloe"
    },
    {
        id: 5,
        name: "Amaryllis",
        commonNames: ["Many, including: Belladonna lily", "Saint Joseph lily", "Cape Belladonna", "Naked Lady"],
        scientificName: "Amaryllis spp.",
        family: "Amaryllidaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/amaryllis"
    },
    {
        id: 6,
        name: "Autumn Crocus",
        commonNames: ["Meadow Saffron"],
        scientificName: "Colchicum autumnale",
        family: "Liliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/autumn-crocus"
    },
    {
        id: 7,
        name: "Azalea",
        commonNames: ["Rosebay", "Rhododendron"],
        scientificName: "Rhododendron spp",
        family: "Ericaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/azalea"
    },
    {
        id: 8,
        name: "Baby's Breath",
        commonNames: ["Maidens Breath"],
        scientificName: "Gypsophila elegans",
        family: "Caryophyllaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/babys-breath"
    },
    {
        id: 9,
        name: "Begonia",
        commonNames: [],
        scientificName: "Begonia spp.",
        family: "Begoniaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/begonia"
    },
    {
        id: 10,
        name: "Boston Ivy",
        commonNames: ["Japanese Ivy", "Woodbine"],
        scientificName: "Parthenocissus tricuspidata",
        family: "Vitaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/boston-ivy"
    },
    {
        id: 11,
        name: "African Violet",
        commonNames: [],
        scientificName: "Saintpaulia spp.",
        family: "Gesneriaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/african-violet"
    },
    {
        id: 12,
        name: "Catnip",
        commonNames: ["Catmint"],
        scientificName: "Nepeta cataria",
        family: "Lamiaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/catnip"
    },
    {
        id: 13,
        name: "Ambrosia Mexicana",
        commonNames: ["Jerusalem Oak", "Feather Geranium"],
        scientificName: "Chenopodium botrys",
        family: "Chenopodiaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/ambrosia-mexicana"
    },
    {
        id: 14,
        name: "American Bittersweet",
        commonNames: ["Bittersweet", "Waxwork", "Shrubby Bittersweet", "False Bittersweet", "Climbing Bittersweet"],
        scientificName: "Celastrus scandens",
        family: "Celastraceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/american-bittersweet"
    },
    {
        id: 15,
        name: "American Holly",
        commonNames: ["English Holly", "European Holly", "Oregon Holly", "Inkberry", "Winterberry"],
        scientificName: "Ilex opaca",
        family: "Aquifoliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/american-holly"
    },
    {
        id: 16,
        name: "American Mandrake",
        commonNames: ["Mayapple", "Indian Apple Root", "Umbrella Leaf", "Wild Lemon", "Hog Apple", "Duck's Foot", "Raccoonberry"],
        scientificName: "Podophyllum peltatum",
        family: "Berberidaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/american-mandrake"
    },
    {
        id: 17,
        name: "American Yew",
        commonNames: ["Canada Yew", "Canadian Yew"],
        scientificName: "Taxus canadensis",
        family: "Taxaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/american-yew"
    },
    {
        id: 18,
        name: "Andromeda Japonica",
        commonNames: ["Pieris", "Lily-of-the-Valley Bush"],
        scientificName: "Pieris japonica",
        family: "Ericaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/andromeda-japonica"
    },
    {
        id: 19,
        name: "Angelica Tree",
        commonNames: ["Hercules' Club", "Devil's Walking Stick", "Prickly Ash", "Prickly Elder"],
        scientificName: "Aralia spinosa",
        family: "Araliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/angelica-tree"
    },
    {
        id: 20,
        name: "Apple",
        commonNames: ["Includes crabapples"],
        scientificName: "Malus sylvestrus",
        family: "Rosaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/apple"
    },
    {
        id: 21,
        name: "Apricot",
        commonNames: ["Group also includes Plum, Peach, Cherry"],
        scientificName: "Prunus armeniaca",
        family: "Rosaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/apricot"
    },
    {
        id: 22,
        name: "Arrow-Head Vine",
        commonNames: ["Nephthytis", "Green Gold Naphthytis", "African Evergreen", "Trileaf Wonder"],
        scientificName: "Syngonium podophyllum",
        family: "Araceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/arrow-head-vine"
    },
    {
        id: 23,
        name: "Arum Lily",
        commonNames: ["Calla Lily", "Pig Lily", "White Arum", "Trumpet Lily", "Florist's Calla", "Garden Calla"],
        scientificName: "Zantedeschia aethiopica",
        family: "Araceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/arum-lily"
    },
    {
        id: 24,
        name: "Asian Lily",
        commonNames: ["Asiatic Lily"],
        scientificName: "Lilium asiatica",
        family: "Liliaceae",
        isToxicToDogs: false,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/asian-lily"
    },
    {
        id: 25,
        name: "Asparagus Fern",
        commonNames: ["Asparagus", "Emerald Feather", "Emerald Fern", "Sprengeri Fern", "Plumosa Fern", "Lace Fern", "Racemose Asparagus", "Shatavari"],
        scientificName: "Asparagus densiflorus cv sprengeri",
        family: "Liliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/asparagus-fern"
    },
    {
        id: 26,
        name: "Australian Ivy Palm",
        commonNames: ["Schefflera", "Umbrella Tree", "Octopus Tree", "Starleaf"],
        scientificName: "Brassaia actinophylla",
        family: "Araliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/schefflera"
    },
    {
        id: 27,
        name: "Baby Doll Ti Plant",
        commonNames: ["Ti-Plant", "Good-Luck Plant", "Hawaiian Ti Plant"],
        scientificName: "Cordyline terminalis",
        family: "Agavaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/ti-plant"
    },
    {
        id: 28,
        name: "Barbados Aloe",
        commonNames: ["Medicine Plant", "True Aloe"],
        scientificName: "Aloe barbadensis",
        family: "Aloaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/aloe"
    },
    {
        id: 29,
        name: "Barbados Lily",
        commonNames: ["Amaryllis", "Fire Lily", "Lily of the Palace", "Ridderstjerne"],
        scientificName: "Hippeastrum spp.",
        family: "Amaryllidaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/barbados-lily"
    },
    {
        id: 30,
        name: "Barbados Pride",
        commonNames: ["Peacock Flower", "Dwarf Poinciana", "Brazilwood"],
        scientificName: "Caesalpinia pulcherrima",
        family: "Fabaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/barbados-pride"
    },
    {
        id: 31,
        name: "Bird of Paradise Bush",
        commonNames: ["Bird of Paradise", "Poinciana"],
        scientificName: "Poinciana gilliesii",
        family: "Leguminosae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bird-paradise-bush"
    },
    {
        id: 32,
        name: "Acorn Squash",
        commonNames: ["Squash"],
        scientificName: "Cucurbita pepo",
        family: "Cucurbitaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/acorn-squash"
    },
    {
        id: 33,
        name: "African Daisy",
        commonNames: ["Cape Marigold", "Star of the Veldt"],
        scientificName: "Dimorphotheca pluvialis",
        family: "Compositae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/african-daisy"
    },
    {
        id: 34,
        name: "Algaroba",
        commonNames: ["Mesquite", "Ironwood"],
        scientificName: "Prosopis juliflora",
        family: "Leguminosae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/algaroba"
    },
    {
        id: 35,
        name: "Alsike Clover",
        commonNames: [],
        scientificName: "Trifolium hybridum",
        family: "Leguminosae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/alsike-clover"
    },
    {
        id: 36,
        name: "Aluminum Plant",
        commonNames: ["Watermelon Plant"],
        scientificName: "Pilea cadierei",
        family: "Urticaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/aluminum-plant"
    },
    {
        id: 37,
        name: "Alumroot",
        commonNames: ["Coral Bells", "Heuchera"],
        scientificName: "Heuchera sanguinea",
        family: "Saxifragaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/alumroot"
    },
    {
        id: 38,
        name: "Alyssum",
        commonNames: ["Sweet Alyssum"],
        scientificName: "Alyssum spp.",
        family: "Cruciferae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/alyssum"
    },
    {
        id: 39,
        name: "American Rubber Plant",
        commonNames: ["Peperomia", "Baby Rubber Plant", "Blunt Leaf Peperomia"],
        scientificName: "Peperomia obtusifolia",
        family: "Piperaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/peperomia"
    },
    {
        id: 40,
        name: "Japanese Yew",
        commonNames: ["Yew", "English Yew"],
        scientificName: "Taxus cuspidata",
        family: "Taxaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/yew"
    },
    {
        id: 41,
        name: "Amur Maple",
        commonNames: [],
        scientificName: "Acer ginnala",
        family: "Aceraceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/amur-maple"
    },
    {
        id: 42,
        name: "Spider Plant",
        commonNames: ["Ribbon Plant", "Anthericum Comosum"],
        scientificName: "Chlorophytum comosum",
        family: "Anthericaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/spider-plant"
    },
    {
        id: 43,
        name: "Snapdragon",
        commonNames: ["Antirrhinum Multiflorum"],
        scientificName: "Antirrhinum spp.",
        family: "Scrophulariaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/snapdragon"
    },
    {
        id: 44,
        name: "Arabian Gentian",
        commonNames: ["Prairie Gentian", "Lisianthus", "Texas Bluebell"],
        scientificName: "Lisianthus russellianum",
        family: "Gentianaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/arabian-gentian"
    },
    {
        id: 45,
        name: "Areca Palm",
        commonNames: ["Golden Butterfly Palm", "Cane Palm", "Golden Feather Palm", "Yellow Palm"],
        scientificName: "Dypsis lutescens",
        family: "Araceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/areca-palm"
    },
    {
        id: 46,
        name: "Blushing Bromeliad",
        commonNames: ["Aregelia", "Bromeliad"],
        scientificName: "Neoregelia spp.",
        family: "Bromeliaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/blushing-bromeliad"
    },
    {
        id: 47,
        name: "Artillery Plant",
        commonNames: [],
        scientificName: "Pilea microphylla",
        family: "Urticaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/artillery-plant"
    },
    {
        id: 48,
        name: "Fish Tail Fern",
        commonNames: ["Aspidium falcatum"],
        scientificName: "Cyrtomium falcatum",
        family: "Polypodiaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/fish-tail-fern"
    },
    {
        id: 49,
        name: "Macadamia Nut",
        commonNames: ["Australian Nut"],
        scientificName: "Macadamia integrifolia",
        family: "Proteaceae",
        isToxicToDogs: true,
        isToxicToCats: false,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/macadamia-nut"
    },
    {
        id: 50,
        name: "Australian Pine",
        commonNames: ["Norfolk Pine", "House Pine"],
        scientificName: "Araucaria heterophylla",
        family: "Araucariaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/australian-pine"
    },
    {
        id: 51,
        name: "Autumn Olive",
        commonNames: [],
        scientificName: "Elaeagnus umbellata",
        family: "Elaeagnaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/autumn-olive"
    },
    {
        id: 52,
        name: "Avocado",
        commonNames: [],
        scientificName: "Persea americana",
        family: "Lauraceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/avocado"
    },
    {
        id: 53,
        name: "Baby's Tears",
        commonNames: [],
        scientificName: "Soleirolia soleirolii",
        family: "Urticaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/babys-tears"
    },
    {
        id: 54,
        name: "Bachelor's Buttons",
        commonNames: ["Cornflower", "Bluebottle"],
        scientificName: "Centaurea cyanus",
        family: "Compositae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bachelors-buttons"
    },
    {
        id: 55,
        name: "Ball Fern",
        commonNames: [],
        scientificName: "Davallia spp.",
        family: "Polypodiaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/ball-fern"
    },
    {
        id: 56,
        name: "Bamboo",
        commonNames: ["Golden Bamboo", "Fishpole Bamboo"],
        scientificName: "Phyllostachys aurea",
        family: "Gramineae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bamboo"
    },
    {
        id: 57,
        name: "Bamboo Palm",
        commonNames: ["Good Luck Palm", "Parlor Palm", "Miniature Fish Tail Dwarf Palm"],
        scientificName: "Chamaedorea elegans",
        family: "Palmae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bamboo-palm"
    },
    {
        id: 58,
        name: "Bamboo Vine",
        commonNames: ["Smilax", "Blaspheme Vine", "Bristly Greenbrier", "Bullbrier"],
        scientificName: "Smilax spp.",
        family: "Liliaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bamboo-vine"
    },
    {
        id: 59,
        name: "Banana",
        commonNames: [],
        scientificName: "Musa acuminata",
        family: "Musaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/banana"
    },
    {
        id: 60,
        name: "Banana Squash",
        commonNames: ["Squash", "Buttercup Squash"],
        scientificName: "Cucurbita maxima",
        family: "Cucurbitaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/banana-squash"
    },
    {
        id: 61,
        name: "Barberton Daisy",
        commonNames: ["Transvaal Daisy", "Gerbera Daisy", "African Daisy"],
        scientificName: "Gerbera jamesonii",
        family: "Compositae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/barberton-daisy"
    },
    {
        id: 62,
        name: "Barnaby's Thistle",
        commonNames: ["Yellow Star Thistle"],
        scientificName: "Centaurea solstitialis",
        family: "Compositae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/barnabys-thistle"
    },
    {
        id: 63,
        name: "Basil",
        commonNames: [],
        scientificName: "Ocimum basilicum",
        family: "Lamiaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/basil"
    },
    {
        id: 64,
        name: "Bay Laurel",
        commonNames: ["Sweet Bag", "Bay Tree", "Tree Laurel", "Laurel Tree", "Laurel"],
        scientificName: "Laurus nobilis",
        family: "Lauraceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bay-laurel"
    },
    {
        id: 65,
        name: "Bead Tree",
        commonNames: ["Chinaberry Tree", "White Cedar", "Texas Umbrella Tree"],
        scientificName: "Melia azedarach",
        family: "Meliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/chinaberry-tree"
    },
    {
        id: 66,
        name: "Beet",
        commonNames: ["Beets"],
        scientificName: "Beta vulgaris",
        family: "Chenopodiaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/beet"
    },
    {
        id: 67,
        name: "Climbing Begonia",
        commonNames: ["Rex Begonia Vine", "Trailing Begonia"],
        scientificName: "Cissus dicolor",
        family: "Vitaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/climbing-begonia"
    },
    {
        id: 68,
        name: "Belmore Sentry Palm",
        commonNames: ["Curly Palm", "Kentia Palm"],
        scientificName: "Howea forsteriana",
        family: "Palmae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/belmore-sentry-palm"
    },
    {
        id: 69,
        name: "Bergamot Orange",
        commonNames: [],
        scientificName: "Citrus bergamia",
        family: "Rutaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bergamot-orange"
    },
    {
        id: 70,
        name: "Shagbark Hickory",
        commonNames: ["Hickory", "Water Hickory", "Bitter Pecan", "Bitternut"],
        scientificName: "Carya ovata",
        family: "Juglandaceae",
        isToxicToDogs: true,
        isToxicToCats: false,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/hickory"
    },
    {
        id: 71,
        name: "Bird of Paradise Flower",
        commonNames: ["Crane Flower", "Bird's Tongue Flower"],
        scientificName: "Strelitzia reginae",
        family: "Strelitziaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bird-of-paradise-flower"
    },
    {
        id: 72,
        name: "Bishop's Weed",
        commonNames: ["Greater Ammi", "False Queen Anne's Lace"],
        scientificName: "Ammi majus",
        family: "Apiaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bishops-weed"
    },
    {
        id: 73,
        name: "Bitter Root",
        commonNames: [],
        scientificName: "Lewisia rediviva",
        family: "Portulacaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bitter-root"
    },
    {
        id: 74,
        name: "Black Calla",
        commonNames: ["Solomon's Lily", "Wild Calla", "Wild Arum"],
        scientificName: "Arum palaestinum",
        family: "Araceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/black-calla"
    },
    {
        id: 75,
        name: "Black Cherry",
        commonNames: ["Wild Cherry", "Rum Cherry"],
        scientificName: "Prunus serotina",
        family: "Rosaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/black-cherry"
    },
    {
        id: 76,
        name: "Hawthorn",
        commonNames: ["Black Haw", "Black Hawthorn"],
        scientificName: "Crataegus species",
        family: "Rosaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/hawthorn"
    },
    {
        id: 77,
        name: "Dog Hobble",
        commonNames: ["Dog Laurel", "Black Laurel", "Fetter Bush", "Drooping Leucothoe"],
        scientificName: "Leucothoe species",
        family: "Ericaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/dog-hobble"
    },
    {
        id: 78,
        name: "Black Nightshade",
        commonNames: ["Deadly Nightshade", "Nightshade"],
        scientificName: "Solanum nigrum",
        family: "Solanaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/black-nightshade"
    },
    {
        id: 79,
        name: "Black Walnut",
        commonNames: [],
        scientificName: "Juglans nigra",
        family: "Juglandaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/black-walnut"
    },
    {
        id: 80,
        name: "Ponderosa Pine",
        commonNames: ["Blackjack Pine", "Western Yellow Pine", "Yellow Pine", "Bull Pine"],
        scientificName: "Pinus ponderosa",
        family: "Pinaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/ponderosa-pine"
    },
    {
        id: 81,
        name: "Bloodleaf",
        commonNames: ["Beefsteak Plant", "Chicken Gizzard", "Joseph's Coat"],
        scientificName: "Iresine herbstii",
        family: "Amaranthaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bloodleaf"
    },
    {
        id: 82,
        name: "Blooming Sally",
        commonNames: ["Great Willow-Herb", "Fire Weed", "Willow Herb"],
        scientificName: "Epilobium angustifolium",
        family: "Onagraceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/blooming-sally"
    },
    {
        id: 83,
        name: "Blue Bead",
        commonNames: ["Corn Lily", "Clintonia"],
        scientificName: "Clintonia borealis",
        family: "Liliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/blue-bead"
    },
    {
        id: 84,
        name: "Blue Daisy",
        commonNames: ["Blue Marguerite"],
        scientificName: "Felicia amelloides",
        family: "Compositae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/blue-daisy"
    },
    {
        id: 85,
        name: "Blue Echeveria",
        commonNames: ["Hens and Chickens", "Hen and Biddies", "Maroon Chenille Plant"],
        scientificName: "Echeveria glauca",
        family: "Crassulaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/blue-echeveria"
    },
    {
        id: 86,
        name: "Blue-eyed Daisy",
        commonNames: ["African Daisy", "Cape Daisy", "Blue Eyed African Daisy"],
        scientificName: "Arctotis stoechadifolia",
        family: "Compositae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/blue-eyed-daisy"
    },
    {
        id: 87,
        name: "Blue Dicks",
        commonNames: ["Wild Hyacinth", "Purplehead"],
        scientificName: "Dichelostemma capitatum",
        family: "Amaryllidaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/blue-dicks"
    },
    {
        id: 88,
        name: "Bog Laurel",
        commonNames: ["Pale Laurel"],
        scientificName: "Kalmia polifolia",
        family: "Ericaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bog-laurel"
    },
    {
        id: 89,
        name: "Bold Sword Fern",
        commonNames: ["Sword Fern"],
        scientificName: "Nephrolepis biserrata",
        family: "Dryopteridaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bold-sword-fern"
    },
    {
        id: 90,
        name: "Borage",
        commonNames: ["Starflower"],
        scientificName: "Borago officinalis",
        family: "Boraginaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/borage"
    },
    {
        id: 91,
        name: "Boston Fern",
        commonNames: [],
        scientificName: "Nephrolepis exalta bostoniensis",
        family: "Dryopteridaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/boston-fern"
    },
    {
        id: 92,
        name: "Ponytail Palm",
        commonNames: ["Bottle Palm", "Elephant-foot Tree"],
        scientificName: "Nolina recurvata",
        family: "Agavaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/ponytail-palm"
    },
    {
        id: 93,
        name: "Bottlebrush",
        commonNames: ["Weeping Bottlebrush"],
        scientificName: "Callistemon spp.",
        family: "Myrtaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bottlebrush"
    },
    {
        id: 94,
        name: "Boxwood",
        commonNames: [],
        scientificName: "Buxus spp.",
        family: "Buxaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/boxwood"
    },
    {
        id: 95,
        name: "Bracken Fern",
        commonNames: ["Brake Fern", "Eagle Fern"],
        scientificName: "Pteridium aquilinum",
        family: "Polypodiaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bracken-fern"
    },
    {
        id: 96,
        name: "Brake Fern",
        commonNames: ["Table Fern", "Cretan Brake Fern"],
        scientificName: "Pteris cretica",
        family: "Pteridaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/brake-fern"
    },
    {
        id: 97,
        name: "English Ivy",
        commonNames: ["Branching Ivy", "Common Ivy", "Glacier Ivy"],
        scientificName: "Hedera helix",
        family: "Araliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/english-ivy"
    },
    {
        id: 98,
        name: "Orchid",
        commonNames: ["Brazilian Orchid"],
        scientificName: "Sophronitis spp.",
        family: "Orchidaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/orchid"
    },
    {
        id: 99,
        name: "Poinciana",
        commonNames: ["Royal Poinciana", "Flamboyant Tree", "Peacock Flower"],
        scientificName: "Delonix regia",
        family: "Fabaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/poinciana"
    },
    {
        id: 100,
        name: "Impatiens",
        commonNames: ["Bread and Butter Plant", "Buzzy Lizzie", "Touch-me-not"],
        scientificName: "Impatiens spp.",
        family: "Balsaminaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/impatiens"
    },
    {
        id: 101,
        name: "Queencup",
        commonNames: ["Bride's Bonnet", "Bead Lily"],
        scientificName: "Clintonia uniflora",
        family: "Liliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/queencup"
    },
    {
        id: 102,
        name: "Broom Hickory",
        commonNames: ["Pignut Hickory"],
        scientificName: "Carya glabra",
        family: "Juglandaceae",
        isToxicToDogs: true,
        isToxicToCats: false,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/hickory"
    },
    {
        id: 103,
        name: "Brunfelsia",
        commonNames: ["Yesterday, Today, Tomorrow", "Morning, Noon and Night", "Kiss-Me-Quick"],
        scientificName: "Brunfelsia species",
        family: "Solanaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/brunfelsia"
    },
    {
        id: 104,
        name: "Buckeye",
        commonNames: ["Horse Chestnut"],
        scientificName: "Aesculus spp.",
        family: "Hippocastanaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/buckeye"
    },
    {
        id: 105,
        name: "Buckwheat",
        commonNames: [],
        scientificName: "Fagopyrum spp.",
        family: "Polygonaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/buckwheat"
    },
    {
        id: 106,
        name: "Buddhist Pine",
        commonNames: ["Yew Pine", "Japanese Yew", "Southern Yew"],
        scientificName: "Podocarpus macrophylla",
        family: "Podocarpaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/buddhist-pine"
    },
    {
        id: 107,
        name: "Bur Gourd",
        commonNames: ["West Indian Gherkin"],
        scientificName: "Cucumis anguria",
        family: "Cucurbitaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/bur-gourd"
    },
    {
        id: 108,
        name: "Burning Bush",
        commonNames: ["Wahoo", "Spindle Tree"],
        scientificName: "Euonymus alatus",
        family: "Celastraceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/burning-bush"
    },
    {
        id: 109,
        name: "Burro's Tail",
        commonNames: ["Donkey's Tail", "Horse's Tail", "Lamb's Tail"],
        scientificName: "Sedum morganianum",
        family: "Crassulaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/burros-tail"
    },
    {
        id: 110,
        name: "Buttercup",
        commonNames: ["Crowfoot", "Figwort"],
        scientificName: "Ranunculus spp.",
        family: "Ranunculaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/buttercup"
    },
    {
        id: 111,
        name: "White Ginger",
        commonNames: ["Butterfly Ginger", "Cinnamon Jasmine", "Garland Flower"],
        scientificName: "Hedychium coronarium",
        family: "Zingiberaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/white-ginger"
    },
    {
        id: 112,
        name: "Butterfly Iris",
        commonNames: ["African Iris", "Fortnight Lily"],
        scientificName: "Dietes iridioides",
        family: "Iridaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/butterfly-iris"
    },
    {
        id: 113,
        name: "Butternut Squash",
        commonNames: ["Squash"],
        scientificName: "Cucurbita moschata",
        family: "Cucurbitaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/butternut-squash"
    },
    {
        id: 114,
        name: "Caladium",
        commonNames: ["Elephant Ears", "Heart of Jesus", "Angel Wings"],
        scientificName: "Caladium hortulanum",
        family: "Araceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/caladium"
    },
    {
        id: 115,
        name: "Calamondin Orange",
        commonNames: [],
        scientificName: "Citrus mitis",
        family: "Rutaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/calamondin-orange"
    },
    {
        id: 116,
        name: "Calathea",
        commonNames: ["Rattlesnake Plant", "Peacock Plant", "Zebra Plant"],
        scientificName: "Calathea spp.",
        family: "Marantaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/rattlesnake-plant"
    },
    {
        id: 117,
        name: "Algerian Ivy",
        commonNames: ["Canary Island Ivy", "Madeira Ivy", "California Ivy"],
        scientificName: "Hedera canariensis",
        family: "Araliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/algerian-ivy"
    },
    {
        id: 118,
        name: "California Pitcher Plant",
        commonNames: ["Cobra Lily", "Cobra Plant"],
        scientificName: "Darlingtonia californica",
        family: "Sarraceniaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/california-pitcher-plant"
    },
    {
        id: 119,
        name: "Sego Lily",
        commonNames: ["Mariposa Lily"],
        scientificName: "Calochortus nuttalli",
        family: "Liliaceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/sego-lily"
    },
    {
        id: 120,
        name: "Camellia",
        commonNames: ["Common Camellia", "Peony Camellia"],
        scientificName: "Camellia japonica",
        family: "Theaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/camellia"
    },
    {
        id: 121,
        name: "Canadian Hemlock",
        commonNames: ["Eastern Hemlock", "Hemlock Spruce"],
        scientificName: "Tsuga canadensis",
        family: "Pinaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/hemlock"
    },
    {
        id: 122,
        name: "Jacaranda",
        commonNames: ["Caeroba", "Jacaranda Tree", "Fern Tree"],
        scientificName: "Jacaranda mimosifolia",
        family: "Bignoniaceae",
        isToxicToDogs: false,
        isToxicToCats: false,
        isNonToxic: true,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/jacaranda"
    },
    {
        id: 123,
        name: "Colocasia",
        commonNames: ["Elephant's Ear", "Taro", "Dasheen", "Coco Yam"],
        scientificName: "Colocasia esculenta",
        family: "Araceae",
        isToxicToDogs: true,
        isToxicToCats: true,
        isNonToxic: false,
        aspcaUrl: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/elephants-ear"
    }
];